no mediainfo at http

diff --git a/vdr-transcode b/vdr-transcode
--- a/vdr-transcode
+++ b/vdr-transcode
@@ -1007,6 +1007,7 @@ parameter() {
 	    exec > trace.log 2>&1
 	    set -x
 	    trace=1
+	    out_stat=
 	    ;;
 	"-trace")
 	    exec > $2 2>&1
@@ -3009,7 +3010,7 @@ analyze() {
     if [ "$scantype" == "" ]
     then
 	which mediainfo 2> /dev/null
-	if [ $? -eq 0 ]
+	if [ $? -eq 0 -a "${INPUT:0:4}" != "http" ]
 	then
 	    echo "Check scantype with mediainfo" >> "$log_c"
 	    scantype=$(mediainfo --Inform="Video;%ScanType/String%" "$input")
@@ -3024,7 +3025,8 @@ analyze() {
 	    vw=$(mediainfo --Inform="Video;%Height%" "$input")
 	    [ "$scantype" == "" ] && check_scantype_ffmpeg
 	else
-	    echo "mediainfo missing, trying ffmpeg" >> "$log_c"
+	    #echo "mediainfo missing, trying ffmpeg" >> "$log_c"
+	    echo "trying ffmpeg" >> "$log_c"
 	    check_scantype_ffmpeg
 	fi
     fi
